New_TechSim/New_TechSim/urls.py
from django.conf.urls import url
from django.contrib import admin
from New_Home.views import *

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home, name="home"),
    url(r'^TechSim/Login/$', Login, name="login"),
    url(r'^TechSim/Logout/$', Logout, name="logout"),
    url(r'^TechSim/Register/$', Register, name="register"),
    url(r'^TechSim/Contact-Us/$', ContactUs, name="contact"),
    url(r'^TechSimPLUS_New_Batches_and_Workshops/$', Event_List, name="all_events"),
    url(r'^(?P<course>[\w-]+)/$', Courses_Details, name="course_details"),
    url(r'^Events/(?P<events>[\w-]+)/$', Events_Details, name="events_details"),


    # Admin Panel Url's
url(r'^TechSim/Admin/Dashboard/$', Admin_Home, name="admin_home"),
url(r'^TechSim/Admin/Banners/$', All_Banners, name="banners"),
url(r'^TechSim/Admin/Add_New_Banner/$', Add_New_Banner, name="Add_New_Banner"),
url(r'^TechSim/Admin/Edit_New_Banner/(?P<b_id>[\w-]+)/(?P<type>[\w-]+)/$', Edit_New_Banner, name="edit_New_Banner"),

url(r'^TechSim/Admin/Courses_Categories/(?P<type>[\w-]+)/(?P<c_id>[\w-]+)/$', All_Courses_Categories, name="courses_categories"),
url(r'^TechSim/Admin/Courses/(?P<type>[\w-]+)/(?P<c_id>[\w-]+)/$', All_Courses, name="courses"),
url(r'^TechSim/Admin/Trainers/(?P<type>[\w-]+)/(?P<t_id>[\w-]+)/$', All_Trainers, name="trainers"),
url(r'^TechSim/Admin/Content/(?P<type>[\w-]+)/(?P<c_id>[\w-]+)/$', All_Content, name="content"),

url(r'^TechSim/Admin/Event_Categories/(?P<type>[\w-]+)/(?P<c_id>[\w-]+)/$', All_Events_Categories, name="events_categories"),
url(r'^TechSim/Admin/Events/(?P<type>[\w-]+)/(?P<c_id>[\w-]+)/$', All_Events, name="events"),
url(r'^TechSim/Admin/Add_Events/$', Add_New_Date, name="add_event_date"),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

New_TechSim/New_Home/models.py
from django.db import models
from django.contrib.auth.models import User

class Slider(models.Model):
    img = models.FileField(null=True, blank=True)
    l1 = models.CharField(max_length=500, null=True, blank=True)
    l2 = models.CharField(max_length=500, null=True, blank=True)
    l3 = models.CharField(max_length=500, null=True, blank=True)
    p = models.CharField(max_length=10, null=True, blank=True)

    def __str__(self):
        return self.p

class Trainer(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    review = models.IntegerField(null=True, blank=True)
    position = models.CharField(max_length=200, null=True, blank=True)
    des = models.CharField(max_length=2000, null=True, blank=True)
    mail = models.CharField(max_length=200, null=True, blank=True)
    img = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.name

class Courses_Category(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    date = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name

class Course(models.Model):
    cat = models.ForeignKey(Courses_Category, related_name="cat",null=True, blank=True, on_delete=models.CASCADE)
    cat2 = models.ForeignKey(Courses_Category, related_name="cat2", null=True, blank=True, on_delete=models.CASCADE)
    t1 = models.ForeignKey(Trainer, related_name="Main", null=True, blank=True, on_delete=models.CASCADE)
    t2 = models.ForeignKey(Trainer, related_name="Secondary", null=True, blank=True, on_delete=models.CASCADE)
    url = models.CharField(max_length=500, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    img = models.FileField(null=True, blank=True)
    fee = models.CharField(max_length=200, null=True, blank=True)
    review = models.IntegerField( null=True, blank=True)
    short_des = models.CharField(max_length=1000, null=True, blank=True)
    long_des = models.CharField(max_length=2000, null=True, blank=True)
    seo_des = models.CharField(max_length=2000, null=True, blank=True)
    seo_keys = models.CharField(max_length=2000, null=True, blank=True)
    duration = models.CharField(max_length=200, null=True, blank=True)
    skill = models.CharField(max_length=200, null=True, blank=True)
    students = models.CharField(max_length=200, null=True, blank=True)
    classes = models.CharField(max_length=200, null=True, blank=True)
    l1 = models.CharField(max_length=200, null=True, blank=True)
    l2 = models.CharField(max_length=200, null=True, blank=True)
    l3 = models.CharField(max_length=200, null=True, blank=True)
    l4 = models.CharField(max_length=200, null=True, blank=True)
    l5 = models.CharField(max_length=200, null=True, blank=True)
    l6 = models.CharField(max_length=200, null=True, blank=True)
    l7 = models.CharField(max_length=200, null=True, blank=True)
    l8 = models.CharField(max_length=200, null=True, blank=True)
    l9 = models.CharField(max_length=200, null=True, blank=True)
    l10 = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name


class Title(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    p = models.CharField(max_length=200, null=True, blank=True)
    S1 = models.CharField(max_length=200, null=True, blank=True)
    S2 = models.CharField(max_length=200, null=True, blank=True)
    S3 = models.CharField(max_length=200, null=True, blank=True)
    S4 = models.CharField(max_length=200, null=True, blank=True)
    S5 = models.CharField(max_length=200, null=True, blank=True)
    S6 = models.CharField(max_length=200, null=True, blank=True)
    S7 = models.CharField(max_length=200, null=True, blank=True)
    S8 = models.CharField(max_length=200, null=True, blank=True)
    S9 = models.CharField(max_length=200, null=True, blank=True)
    S10 = models.CharField(max_length=200, null=True, blank=True)
    S11 = models.CharField(max_length=200, null=True, blank=True)
    S12 = models.CharField(max_length=200, null=True, blank=True)
    S13 = models.CharField(max_length=200, null=True, blank=True)
    S14 = models.CharField(max_length=200, null=True, blank=True)
    S15 = models.CharField(max_length=200, null=True, blank=True)


class Event_Category(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    date = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name


class Events(models.Model):
    usr = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    un = models.CharField(max_length=100, null=True, blank=True)
    ps = models.CharField(max_length=100, null=True, blank=True)

    cat = models.ForeignKey(Event_Category, on_delete=models.CASCADE, null=True, blank=True)
    img = models.FileField(null=True, blank=True)
    logo = models.FileField(null=True, blank=True)
    title = models.CharField(max_length=500, null=True, blank=True)
    url = models.CharField(max_length=500, null=True, blank=True)
    address = models.CharField(max_length=500, null=True, blank=True)
    call = models.CharField(max_length=50, null=True, blank=True)
    email = models.CharField(max_length=50, null=True, blank=True)
    map = models.CharField(max_length=2000, null=True, blank=True)
    topic = models.CharField(max_length=200, null=True, blank=True)
    host = models.CharField(max_length=200, null=True, blank=True)
    file = models.FileField(null=True, blank=True)
    duration = models.CharField(max_length=200, null=True, blank=True)
    skill = models.CharField(max_length=200, null=True, blank=True)
    file_url = models.CharField(max_length=500, null=True, blank=True)
    short_des = models.CharField(max_length=1000, null=True, blank=True)
    long_des = models.CharField(max_length=2000, null=True, blank=True)
    seo_des = models.CharField(max_length=2000, null=True, blank=True)
    seo_keys = models.CharField(max_length=2000, null=True, blank=True)
    students = models.CharField(max_length=2000, null=True, blank=True)
    l1 = models.CharField(max_length=200, null=True, blank=True)
    l2 = models.CharField(max_length=200, null=True, blank=True)
    l3 = models.CharField(max_length=200, null=True, blank=True)
    l4 = models.CharField(max_length=200, null=True, blank=True)
    l5 = models.CharField(max_length=200, null=True, blank=True)
    l6 = models.CharField(max_length=200, null=True, blank=True)
    l7 = models.CharField(max_length=200, null=True, blank=True)
    l8 = models.CharField(max_length=200, null=True, blank=True)
    l9 = models.CharField(max_length=200, null=True, blank=True)
    l10 = models.CharField(max_length=200, null=True, blank=True)
    fee = models.CharField(max_length=200, null=True, blank=True)
    time = models.CharField(max_length=200, null=True, blank=True)
    c_num = models.CharField(max_length=200, null=True, blank=True)
    n1 = models.CharField(max_length=200, null=True, blank=True)
    d1 = models.CharField(max_length=200, null=True, blank=True)
    w1 = models.CharField(max_length=200, null=True, blank=True)
    s1 = models.FileField(null=True, blank=True)
    n2 = models.CharField(max_length=200, null=True, blank=True)
    d2 = models.CharField(max_length=200, null=True, blank=True)
    w2 = models.CharField(max_length=200, null=True, blank=True)
    s2 = models.FileField(null=True, blank=True)
    n3 = models.CharField(max_length=200, null=True, blank=True)
    d3 = models.CharField(max_length=200, null=True, blank=True)
    w3 = models.CharField(max_length=200, null=True, blank=True)
    s3 = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.title


class Dates(models.Model):
    Event = models.ForeignKey(Events, on_delete=models.CASCADE, null=True, blank=True)
    certificate = models.BooleanField(default=False)
    start_date = models.DateField(max_length=200, null=True, blank=True)
    end_date = models.DateField(max_length=200, null=True, blank=True)
    date = models.CharField(max_length=200, null=True, blank=True)

New_TechSim/New_Home/templates/Home/Master/Add_New_Banner.html
{% extends 'Home/Master/admin_base.html' %}
{% load static %}
{% block body %}


<script>
    function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#blah')
                        .attr('src', e.target.result);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
</script>


<style>
.container {
  position: relative;
  text-align: center;
  color: white;
}

.bottom-left {
  position: absolute;
  bottom: 8px;
  left: 16px;
}

.top-left {
  position: absolute;
  top: 8px;
  left: 16px;
}

.top-right {
  position: absolute;
  top: 8px;
  right: 16px;
}

.bottom-right {
  position: absolute;
  bottom: 8px;
  right: 16px;
}

.centered {
  position: absolute;
  top: 30%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.centered1 {
  position: absolute;
  top: 38%;
  left: 50%;
  transform: translate(-50%, -50%);
}
.centered2 {
  position: absolute;
  top: 45%;
  left: 50%;
  transform: translate(-50%, -50%);
}
</style>

	<!--Main container start -->
	<main class="ttr-wrapper">
		<div class="container-fluid">
			<div class="db-breadcrumb">
				<h4 class="breadcrumb-title">Add listing</h4>
				<ul class="db-breadcrumb-list">
					<li><a href="add-listing.html#"><i class="fa fa-home"></i>Home</a></li>
					<li>Add listing</li>
				</ul>
			</div>
			<div class="row">
				<!-- Your Profile Views Chart -->
                {% if type = "Edit" %}
				<div class="col-lg-12 m-b30">
					<div class="widget-box">
						<div class="wc-title">
							<h4>Add New Banner</h4>
						</div>
						<div class="widget-inner">
							<form class="edit-profile m-b30" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
								<div class="row">
                                    <div class=" col-12">
                                        <center><img id="blah" src="{{ b.img.url }}" alt="" width="800" /></center>
                                        <div class="centered"><h4> <span style="color:white;" id = "text1">{{ b.l1 }}</span></h4> </div>
                                        <div class="centered1"><h1><span style="color:white;" id = "text2">{{ b.l2 }}</span></h1></div>
                                        <div class="centered2"> <h4> <span style="color:white;" id = "text3">{{ b.l3 }}</span> </h4></div>
									</div>

									<div class="col-12">
										<div class="ml-auto">
											<h3>1. Titles and Images</h3>
										</div>
									</div>
									<div class="form-group col-6">
										<label class="col-form-label">Course title</label>
										<div>
											<input class="form-control" name="l1" type="text" id = "text_in1" value="{{ b.l1 }}"
                                                   onkeyup="Add_Text1();">
										</div>
									</div>
									<div class="form-group col-6">
										<label class="col-form-label">Course title</label>
										<div>
											<input class="form-control" name="l2" type="text" id = "text_in2" value="{{ b.l2 }}"
                                                   onkeyup="Add_Text1();">
										</div>
									</div>

                                    <div class="form-group col-6">
										<label class="col-form-label">Position</label>
										<div>
											<input class="form-control" name="p" type="text" value="{{ b.p }}">
										</div>
									</div>
									<div class="form-group col-6">
										<label class="col-form-label">Banner Image</label>
										<div>
											<input type='file' onchange="readURL(this);" name="image"  />
										</div>
									</div>

									<div class="seperator"></div>

									<div class="col-12 m-t20">
										<div class="ml-auto m-b5">
											<h3>2. Description</h3>
										</div>
									</div>
									<div class="form-group col-12">
										<label class="col-form-label">Course description</label>
										<div>
											<textarea id = "text_in3" onkeyup="Add_Text1();" class="form-control" name = "l3">{{ b.l3 }} </textarea>
										</div>
									</div>

									<div class="col-12">
										<button type="submit" class="btn">Save</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
                {% else %}

                    <div class="col-lg-12 m-b30">
					<div class="widget-box">
						<div class="wc-title">
							<h4>Add New Banner</h4>
						</div>
						<div class="widget-inner">
							<form class="edit-profile m-b30" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
								<div class="row">
                                    <div class=" col-12">
                                        <center><img id="blah" src="" alt="" width="800" /></center>
                                        <div class="centered"><h4> <span style="color:white;" id = "text1"></span></h4> </div>
                                        <div class="centered1"><h1><span style="color:white;" id = "text2"></span></h1></div>
                                        <div class="centered2"> <h4> <span style="color:white;" id = "text3"></span> </h4></div>
									</div>

									<div class="col-12">
										<div class="ml-auto">
											<h3>1. Titles and Images</h3>
										</div>
									</div>
									<div class="form-group col-6">
										<label class="col-form-label">Course title</label>
										<div>
											<input class="form-control" name="l1" type="text" id = "text_in1" value=""
                                                   onkeyup="Add_Text1();">
										</div>
									</div>
									<div class="form-group col-6">
										<label class="col-form-label">Course title</label>
										<div>
											<input class="form-control" name="l2" type="text" id = "text_in2" value=""
                                                   onkeyup="Add_Text1();">
										</div>
									</div>

                                    <div class="form-group col-6">
										<label class="col-form-label">Position</label>
										<div>
											<input class="form-control" name="p" type="text" value="">
										</div>
									</div>
									<div class="form-group col-6">
										<label class="col-form-label">Banner Image</label>
										<div>
											<input type='file' onchange="readURL(this);" name="image" required  />
										</div>
									</div>

									<div class="seperator"></div>

									<div class="col-12 m-t20">
										<div class="ml-auto m-b5">
											<h3>2. Description</h3>
										</div>
									</div>
									<div class="form-group col-12">
										<label class="col-form-label">Course description</label>
										<div>
											<textarea id = "text_in3" onkeyup="Add_Text1();" class="form-control" name = "l3"> </textarea>
										</div>
									</div>

									<div class="col-12">
										<button type="submit" class="btn">Save</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>

                {% endif %}
				<!-- Your Profile Views Chart END-->
			</div>
		</div>
	</main>


<script>
function Add_Text1() {
  var text1 = document.getElementById("text_in1").value;
  var text2 = document.getElementById("text_in2").value;
  var text3 = document.getElementById("text_in3").value;
  document.getElementById("text1").innerHTML = text1;
  document.getElementById("text2").innerHTML = text2;
  document.getElementById("text3").innerHTML = text3;
}

</script>

{% endblock %}

New_TechSim/New_Home/templates/Home/Master/Add_New_Event_Date.html
{% extends 'Home/Master/admin_base.html' %}
{% load static %}
{% block body %}


<script>
    function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#blah')
                        .attr('src', e.target.result);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
</script>


<style>
.container {
  position: relative;
  text-align: center;
  color: white;
}

.bottom-left {
  position: absolute;
  bottom: 8px;
  left: 16px;
}

.top-left {
  position: absolute;
  top: 8px;
  left: 16px;
}

.top-right {
  position: absolute;
  top: 8px;
  right: 16px;
}

.bottom-right {
  position: absolute;
  bottom: 8px;
  right: 16px;
}

.centered {
  position: absolute;
  top: 30%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.centered1 {
  position: absolute;
  top: 38%;
  left: 50%;
  transform: translate(-50%, -50%);
}
.centered2 {
  position: absolute;
  top: 45%;
  left: 50%;
  transform: translate(-50%, -50%);
}
</style>

	<!--Main container start -->
	<main class="ttr-wrapper">
		<div class="container-fluid">
			<div class="db-breadcrumb">
				<ul class="db-breadcrumb-list">
					<li><a href="{% url 'home' %}"><i class="fa fa-home"></i>Home</a></li>
					<li><a href="{% url 'events' 'Main' 0 %}">Events</a></li>
					<li>Add New Date</li>
				</ul>
			</div>
			<div class="row">


                    <div class="col-lg-12 m-b30">
					<div class="widget-box">
						<div class="wc-title">
							<h4>Add New Course Title</h4>
						</div>
						<div class="widget-inner">
							<form class="edit-profile m-b30" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
								<div class="row">

									<div class="col-12">
										<div class="ml-auto">
											<h3>1. Course Title</h3>
										</div>
									</div>
									<div class="form-group col-6">
										<label class="col-form-label">Choose Course</label>
										<div>
											{{ form.Event }}
										</div>
									</div>
									<div class="form-group col-6">
										<label class="col-form-label">Title</label>
										<div>
											{{ form.start_date }}
										</div>
									</div>

									<div class="form-group col-6">
										<label class="col-form-label">Title Position</label>
										<div>
											{{ form.end_date }}
										</div>
									</div>

                                    <div class="form-group col-6">
										<label class="col-form-label">Title Position</label>
										<div>
											{{ form.date }}
										</div>
									</div>

									<div class="col-12">
										<button type="submit" class="btn">Save</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>

				<!-- Your Profile Views Chart END-->
			</div>
		</div>
	</main>


<script>
function Add_Text1() {
  var text1 = document.getElementById("text_in1").value;
  var text2 = document.getElementById("text_in2").value;
  var text3 = document.getElementById("text_in3").value;
  document.getElementById("text1").innerHTML = text1;
  document.getElementById("text2").innerHTML = text2;
  document.getElementById("text3").innerHTML = text3;
}

</script>

{% endblock %}

New_TechSim/New_Home/templates/Home/Master/all_content.html
{% extends 'Home/Master/admin_base.html' %}
{% load static %}
{% block body %}


	<!--Main container start -->
	<main class="ttr-wrapper">
		<div class="container-fluid">
			<div class="db-breadcrumb">
				<ul class="db-breadcrumb-list">
					<li><a href="courses.html#"><i class="fa fa-home"></i>Home</a></li>
					<li>Courses</li>
				</ul>
			</div>
			<div class="row">
				<!-- Your Profile Views Chart -->
				<div class="col-lg-12 m-b30">
					<div class="widget-box">
						<div class="wc-title">
							<a href="{% url 'content' 'Add' c_id %}" class="btn green radius-xl outline">Add New Content</a>
						</div>
						<div class="widget-inner">
							{% for i in titles %}<div class="card-courses-list admin-courses">
								<div class="card-courses-full-dec">
									<div class="card-courses-title">
                                        <h4>{{ forloop.counter }}. {{ i.name }}
                                            <a href="{% url 'content' 'Edit' i.id %}"><i class="fa fa-pencil"></i></a>
                                            <a href="{% url 'content' 'Delete' i.id %}"><i class="fa fa-trash"></i></a>
                                        </h4>
									</div>
									<div style="padding-left:50px;">
										<ul class="">
											{% if i.S1 %}<li>{{ i.S1 }}</li>{% endif %}
                                            {% if i.S2 %}<li>{{ i.S2 }}</li>{% endif %}
                                            {% if i.S3 %}<li>{{ i.S3 }}</li>{% endif %}
                                            {% if i.S4 %}<li>{{ i.S4 }}</li>{% endif %}
                                            {% if i.S5 %}<li>{{ i.S5 }}</li>{% endif %}
                                            {% if i.S6 %}<li>{{ i.S6 }}</li>{% endif %}
                                            {% if i.S7 %}<li>{{ i.S7 }}</li>{% endif %}
                                            {% if i.S8 %}<li>{{ i.S8 }}</li>{% endif %}
                                            {% if i.S9 %}<li>{{ i.S9 }}</li>{% endif %}
                                            {% if i.S10 %}<li>{{ i.S10 }}</li>{% endif %}
                                            {% if i.S11 %}<li>{{ i.S11 }}</li>{% endif %}
                                            {% if i.S12 %}<li>{{ i.S12 }}</li>{% endif %}
                                            {% if i.S13 %}<li>{{ i.S13 }}</li>{% endif %}
                                            {% if i.S14 %}<li>{{ i.S14 }}</li>{% endif %}
                                            {% if i.S15 %}<li>{{ i.S15 }}</li>{% endif %}
										</ul>
									</div>

								</div>
							</div>
							{% endfor %}


						</div>
					</div>
				</div>
				<!-- Your Profile Views Chart END-->
			</div>
		</div>
	</main>


{% endblock %}

New_TechSim/New_Home/templates/Home/Master/courses_categories.html
{% extends 'Home/Master/admin_base.html' %}
{% load static %}
{% block body %}

<!--Main container start -->
	<main class="ttr-wrapper">
		<div class="container-fluid">
			<div class="db-breadcrumb">
				<ul class="db-breadcrumb-list">
					<li><a href="{% url 'home' %}"><i class="fa fa-home"></i>Home</a></li>
					<li>All Courses Category</li>
				</ul>
			</div>
			<div class="row">
				<!-- Your Profile Views Chart -->
				<div class="col-lg-6 m-b30">
					<div class="widget-box">
						<div class="wc-title">
							<h4>All Courses Categories</h4>
						</div>
						<div class="widget-inner">
							<div class="orders-list">
								<ul>
									{% for i in cats %}
									<li>
										<span class="orders-title">
											<a href="" class="orders-title-name">{{ forloop.counter }}. {{ i.name }} </a>
											<span class="orders-info">Number of Courses: {{ i.course_set.all.count }} | Date: {{ i.date }}</span>
										</span>
										<span class="orders-btn">

                                            <a href="{% url 'courses_categories' 'Edit' i.id %}" class="btn button-sm green">Edit</a>
											<a href= "{% url 'courses_categories' 'Delete' i.id %}" class="btn button-sm red">Delete</a>
										</span>
									</li>
									{% endfor %}
								</ul>
							</div>
						</div>
					</div>
				</div>


				<div class="col-lg-6 m-b30">
					<div class="widget-box">
						<div class="wc-title">
							<h4>Add New Category</h4>
						</div>
						<div class="widget-inner">
							<form class="edit-profile m-b30" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
								<div class="row">
									<div class="col-12">
										<div class="ml-auto">
											<h3>Add New Course Category</h3>
										</div>
									</div>
									<div class="form-group col-10">
										<label class="col-form-label">Course Category </label>
										<div>
											<input class="form-control" name="name" type="text" id = "text_in1" value="{{ cat.name }}"
											>
										</div>
									</div>

									<div class="col-12">
										<button type="submit" class="btn">Add</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
				<!-- Your Profile Views Chart END-->
			</div>
		</div>
	</main>

{% endblock %}

New_TechSim/New_Home/templates/Home/Master/events.html
{% extends 'Home/Master/admin_base.html' %}
{% load static %}
{% block body %}


	<!--Main container start -->
	<main class="ttr-wrapper">
		<div class="container-fluid">
			<div class="db-breadcrumb">
				<h4 class="breadcrumb-title">Courses</h4>
				<ul class="db-breadcrumb-list">
					<li><a href="courses.html#"><i class="fa fa-home"></i>Home</a></li>
					<li>Courses</li>
				</ul>
			</div>
			<div class="row">
				<!-- Your Profile Views Chart -->
				<div class="col-lg-12 m-b30">
					<div class="widget-box">
						<div class="wc-title">
							<a href="{% url 'events' 'Add' 0 %}" class="btn green radius-xl outline">Add New Event</a>
						</div>
						<div class="widget-inner">
							{% for i in courses %}<div class="card-courses-list admin-courses">
								<div class="card-courses-media">
									<img src="{{ i.img.url }}" alt="i.name"/>
								</div>
								<div class="card-courses-full-dec">
									<div class="card-courses-title">
										<h4>{{ i.name }}</h4>
									</div>
									<div class="card-courses-list-bx">
										<ul class="card-courses-view">

											<li class="card-courses-categories">
												<h5>Category</h5>
												<h4>{{ i.cat }}</h4>
											</li>
											<li class="card-courses-stats">
												<a href="courses.html#" class="btn button-sm green radius-xl">{{ i.date }}</a>
											</li>
											<li class="card-courses-price">
												<h5 class="text-primary">&#8377; {{ i.fee }}</h5>
											</li>
										</ul>

										<ul class="card-courses-view">
											{% for d in i.dates_set.all %}<li>{{ forloop.counter }}. {{ d.start_date }}</li>{% endfor %}
										</ul>
									</div>
									<div class="row card-courses-dec">
										<div class="col-md-12">
											<h6 class="m-b10">Event Description</h6>
											<p>{{ i.short_des }}</p>
										</div>
										<div class="col-md-12">
											<a href="{% url 'events' 'Edit' i.id %}" class="btn green radius-xl outline">Edit</a>
											<a href="{% url 'events' 'Delete' i.id %}" class="btn red outline radius-xl ">Delete</a>
											<a href="{% url 'add_event_date' %}" class="btn bnt-info radius-xl "><b style="color:white;">Add Event Date</b></a>
										</div>
									</div>

								</div>
							</div>
							{% endfor %}


						</div>
					</div>
				</div>
				<!-- Your Profile Views Chart END-->
			</div>
		</div>
	</main>


{% endblock %}