FashionHub/FashionHub/urls.py
from django.conf.urls import url
from django.contrib import admin
from shopping.views import *
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home, name='home'),
    url(r'^about/$',About,name='about'),
    url(r'^login/$',Login,name='login'),
    url(r'^contact/$', Contact, name='contact'),
    url(r'^products/(?P<sub_id>[0-9]+)/$',products,name='products'),
    url(r'^product_details/(?P<p_id>[0-9]+)/$',Product_Details,name='product_detail'),
    url(r'^add_to_cart/(?P<pid>[0-9]+)/$',AddToCart,name='cart'),
    url(r'^remove_product/(?P<cid>[0-9]+)/$',Delete_product_from_cart,name='remove'),
    url(r'^mycart/$',MyCart,name='mycart'),
    url(r'^signup/$',Signup,name='signup'),
    url(r'^payment/(?P<pid>[0-9]+)/$',Payment,name='payment'),
    url(r'^payment_check/$',Payment_check,name='payment_check'),
    url(r'^order_product/(?P<pid>[0-9]+)/$',Order,name='order'),
    url(r'^clear_cart/$',Clear_Cart,name='clearcart'),
    ############### Admin Urls ############
    url(r'^admin_panel/$',Admin_home,name='admin_panel'),
    url(r'^All_cat/$',AllCategory,name='all_cat'),
    url(r'^Add_cat/$',Add_category,name='add_cat'),
    url(r'^all_subcat/$',All_subcategory,name='all_subcat'),
    url(r'^Add_subcat/$',Add_sub_cat,name='add_subcat'),
    url(r'^All_product/$',All_product,name='all_product'),
    url(r'^Add_product/$',Add_product,name='add_product'),
    url(r'^delete_category/(?P<cid>[0-9]+)/$',Delete_cat,name='delete_cat'),
    url(r'^delete_sub_category/(?P<sid>[0-9]+)/$',Delete_subcat,name='delete_subcat'),
    url(r'^delete_product/(?P<pid>[0-9]+)/$',Delete_product,name='delete_pro'),
    url(r'^All_orders/$',All_order,name='all_order'),
    url(r'^user_list/(?P<pid>[0-9]+)/$',Buyer_details,name='user_list'),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

FashionHub/shopping/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User

class User_detail(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50, null=True)
    mobile = models.IntegerField(null=True)
    email = models.EmailField(null=True)
    address = models.TextField(null=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name

class Sub_category(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=50, null=True, blank=True)
    def __str__(self):
        return self.category.name +' -- '+self.name
class Product(models.Model):
    subcategory = models.ForeignKey(Sub_category,on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=100,null=True)
    price = models.CharField(max_length=100,null=True)
    discription = models.TextField(max_length=500,null=True)
    img1 = models.FileField(null=True)
    img2 = models.FileField(null=True)
    img3 = models.FileField(null=True)

    def __str__(self):
        return self.subcategory.name + ' -- ' + self.name

class Add_to_cart(models.Model):
    usr = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    product = models.ForeignKey(Product,on_delete=models.CASCADE,null=True)


class Order_placed(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    address = models.TextField(null=True)


class Payment_ids(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    ids = models.CharField(max_length=100,null=True)

FashionHub/shopping/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login, logout, authenticate
from shopping.models import *
from django.http import HttpResponse
from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives
from django.conf import settings
def all_category():
    all_cat = Category.objects.all()
    return all_cat

def total(u):
    data = Add_to_cart.objects.filter(usr = u)
    total = 0
    for i in data:
        total += int(i.product.price)
    return total

def Home(request):
    products = Product.objects.all().order_by('-id')
    last_five = products[:5]
    sub_cat = Sub_category.objects.all().order_by('-id')
    subcat = sub_cat[:4]
    if request.user.is_authenticated():
     d = {"subcat":subcat,"last_five":last_five,'allcat' : all_category(), 'total': total(request.user)}

    else:
        d = {"subcat":subcat,"last_five":last_five,'allcat': all_category(),}
    return render(request, 'index.html',d)

def About(request):
    if request.user.is_authenticated():
         d = {'allcat': all_category(), 'total': total(request.user)}

    else:
        d = {'allcat': all_category()}

    return render(request, 'about.html', d)


def Contact(request):
    if request.user.is_authenticated():
        d = {'allcat': all_category(), 'total': total(request.user)}

    else:
        d = {'allcat': all_category()}
    return render(request, 'contact.html', d)

def products(request, sub_id):
    data = Sub_category.objects.filter(id = sub_id).first()
    if request.user.is_authenticated():
         d = {'allcat': all_category(),'subcat':data, 'total': total(request.user)}

    else:
        d = {'allcat': all_category(),'subcat':data,}
    return render(request,'products.html',d)

def Product_Details(request,p_id):
    pdata = Product.objects.filter(id = p_id).first()
    if request.user.is_authenticated():
      d = {'allcat': all_category(),"product":pdata, 'total': total(request.user)}
    else:
        d = {'allcat': all_category(), "product": pdata}

    return render(request,'product_details.html',d)


def Login(request):
    error = False

    if request.method == 'POST':
        u = request.POST['user']
        p = request.POST['pwd']
        us = authenticate(username = u, password = p)
        if us:
            login(request,us)
            if request.user.is_staff:
              return redirect('admin_panel')
            else:
                return redirect('home')
        else:

            error = True
    d = {'allcat': all_category, 'error':error}
    return render(request,'login.html',d)

def AddToCart(request,pid):
    data = Product.objects.filter(id=pid).first()
    dd = Add_to_cart.objects.filter(product =data,usr = request.user)
    if dd:
        return redirect('mycart')
    else:
        Add_to_cart.objects.create(usr = request.user,product=data)
        return redirect('mycart')

def MyCart(request):
    mycart = Add_to_cart.objects.filter(usr=request.user)
    total = 0
    for i in mycart:
        total += int(i.product.price)
    d = {'allcat': all_category(), 'mycart': mycart, 'total': total}
    return render(request,'cart.html',d)

def Delete_product_from_cart(request,cid):
    data = Add_to_cart.objects.filter(id = cid).first()
    data.delete()
    return redirect('mycart')

def Signup(request):
    error = False
    if request.method=='POST':
        u = request.POST['user']
        p = request.POST['pwd']
        n = request.POST['name']
        m = request.POST['mob']
        e = request.POST['email']
        a = request.POST['add']
        user_data = User.objects.filter(username = u)
        if user_data:
            error = True
        else:
            user = User.objects.create_user(username = u, password= p)
            User_detail.objects.create(user = user,name = n, mobile = m,
                                       email = e,address= a)
            return redirect('login')
    d = {'allcat': all_category(),'error':error}
    return render(request,'signup.html',d)


def Order(request,pid):
    data = User_detail.objects.filter(user = request.user).first()
    address = data.address
    d = {'allcat': all_category(),'address': address, 'total':total(request.user)}
    if request.method == "POST":
        add = request.POST['add']
        product = Product.objects.filter(id = pid).first()
        data2 = Add_to_cart.objects.filter(product = product,usr=request.user)
        data2.delete()
        Order_placed.objects.create(user = request.user,product = product,address=add)
        sub = "Order Placed"
        from_email = settings.EMAIL_HOST_USER
        d = {"name":data.name,"product":product.name,
             "price":product.price,"des":product.discription}
        html = get_template('mail.html').render(d)
        msg = EmailMultiAlternatives(sub,' ',from_email,[data.email])
        msg.attach_alternative(html,'text/html')
        #msg.send()

        return redirect('payment',pid)
    return render(request,'order.html',d)

def Clear_Cart(request):
    data = Add_to_cart.objects.filter(usr=request.user)
    data.delete()
    return redirect('home')

import requests
import json


headers = {"X-Api-Key": "36fedc81de23f05b7044ababd27d0555",
           "X-Auth-Token": "6fb6c5ad36a9baa8a7c734141a9535f3"}

def Payment(request,pid):
    product = Product.objects.filter(id = pid).first()
    user = User_detail.objects.filter(user = request.user).first()
    payload = {
        "purpose":"Product Payment",
        "amount":product.price,
        "buyer_name":user.name,
        "email":user.email,
        "phone":user.mobile,
        "send_email":True,
        "send_sms":True,
        "redirect_url":"http://127.0.0.1:8000/payment_check/"
    }
    response = requests.post("https://www.instamojo.com/api/1.1/payment-requests/",
                            data=payload,headers=headers)
    print(response)
    y = response.text
    d = json.loads(y)
    a = d['payment_request']['longurl']
    i = d['payment_request']['id']
    Payment_ids.objects.create(ids = i,user = request.user)
    return redirect(a)

def Payment_check(request):
    i = Payment_ids.objects.filter(user = request.user).first()
    ii = i.ids
    response = requests.get("https://www.instamojo.com/api/1.1/payment-requests/"+str(ii)+'/',
                            headers=headers)
    y = response.text
    b = json.loads(y)
    print(b)
    status = b['payment_request']['status']
    if status=="Completed":
        return HttpResponse('Done')
    else:
        return HttpResponse("Fail")


def Admin_home(request):
    return render(request,'admin_home.html')

def AllCategory(request):
    data = Category.objects.all()
    d = {"allcat":data}
    return render(request,'allcat.html',d)

def Add_category(request):
    if request.method == "POST":
        n = request.POST['cat']
        Category.objects.create(name = n)
        return redirect('all_cat')
    return render(request,'add_category.html')

def All_subcategory(request):
    data = Sub_category.objects.all()
    d = {"allsubcat":data}
    return render(request,'all_subcat.html',d)


def Add_sub_cat(request):
    all_cat = Category.objects.all()
    d = {"allcat":all_cat}
    if request.method == "POST":
        c = request.POST['cid']
        cat = Category.objects.get(id = c)
        n = request.POST['subcat']
        Sub_category.objects.create(category = cat,name = n)
        return redirect('all_subcat')
    return render(request,'add_subcat.html',d)


def All_product(request):
    all_product = Product.objects.all()
    d = {"all_product":all_product}
    return render(request,'all_product.html',d)

def Add_product(request):
    all_subcat = Sub_category.objects.all()
    d = {"allsubcat":all_subcat}
    if request.method == "POST":
        s = request.POST['sid']
        subcat = Sub_category.objects.get(id = s)
        n = request.POST['name']
        p = request.POST['price']
        d = request.POST['dis']
        i1 = request.FILES['img1']
        i2 = request.FILES['img2']
        i3 = request.FILES['img3']
        Product.objects.create(subcategory = subcat,name = n,price = p,discription = d,
                               img1 = i1,img2=i2,img3 = i3)
        return redirect('all_product')
    return render(request,'add_product.html',d)

def Delete_cat(request,cid):
    data = Category.objects.get(id = cid)
    data.delete()
    return redirect('all_cat')

def Delete_subcat(request,sid):
    data = Sub_category.objects.get(id = sid)
    data.delete()
    return redirect('all_subcat')
def Delete_product(request,pid):
    data = Product.objects.get(id = pid)
    data.delete()
    return redirect('all_product')


def All_order(request):
    all_ordered_product = []
    for i in Product.objects.all():
        data = Order_placed.objects.filter(product = i)
        if data:
            all_ordered_product.append(i)
    d = {"all_ordered_product":all_ordered_product}
    return render(request,'all_order.html',d)


def Buyer_details(request,pid):
   pro = Product.objects.get(id = pid)
   user_list = []
   number = []
   for i in User_detail.objects.all():
       data = Order_placed.objects.filter(user=i.user,product=pro)

       if data:
           number.append(data.count())
           user_list.append(i)
   z = zip(user_list,number)

   d = {"product":pro,"z":z}
   return render(request,'user_list.html',d)

FashionHub/shopping/templates/about.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
<style>
	.page-banner {
  background: rgba(0, 0, 0, 0) url("{% static 'img/background/shop-banner.jpg' %}") no-repeat center center;
  -webkit-background-size: cover;
  background-size: cover;
  text-align: center;
}
</style>
<!-- Page Banner Start -->
<div class="page-banner padding-120 fix">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<h1>About us</h1>
			</div>
		</div>
	</div>
</div><!-- Page Banner End -->
<div class="page-breadcrumb fix">
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<ul>
					<li><a href="about.html#">Home</a></li>
					<li><span>About us</span></li>
				</ul>
			</div>
		</div>
	</div>
</div>
<!-- About Page Start -->
<div class="about-page page margin-70 fix">
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<div class="welcome">
					<h2>welcome to <span>zackas</span></h2>
					<h3>EXCLUSIVE STORE</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.</p>
				</div>
			</div>
			<div class="col-md-6">
				<div class="image">
					<img src="{% static 'img/about-us.jpg' %}" alt="" />
				</div>
			</div>
			<div class="col-md-3">
				<div class="welcome">
					<h2>who <span>we are</span></h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore .</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="our-services fix">
				<div class="col-sm-6">
					<div class="sin-service">
						<h3>Our Mission</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco labis nisi ut aliquip. uis nostrud exercitation ullamco.</p>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="sin-service">
						<h3>OVER 15 YEARS EXPERIENCE</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco labis nisi ut aliquip. uis nostrud exercitation ullamco.</p>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="sin-service">
						<h3>WHAT WE DO</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco labis nisi ut aliquip. uis nostrud exercitation ullamco.</p>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="sin-service">
						<h3>ONLINE ORDERING</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco labis nisi ut aliquip. uis nostrud exercitation ullamco.</p>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="sin-service">
						<h3>OUR CLIENTS</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco labis nisi ut aliquip. uis nostrud exercitation ullamco.</p>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="sin-service">
						<h3>TAILORING FOR FREE</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco labis nisi ut aliquip. uis nostrud exercitation ullamco.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div><!-- About Page End -->	
{% endblock %}

FashionHub/shopping/templates/add_category.html
{% extends 'base2.html' %}
{% block body %}
{% load static %}
<style>
	.page-banner {
  background: rgba(0, 0, 0, 0) url("{% static 'img/background/shop-banner.jpg' %}") no-repeat center center;
  -webkit-background-size: cover;
  background-size: cover;
  text-align: center;
}
</style>
<!-- Page Banner Start -->
<div class="page-banner padding-120 fix">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<h1>Add Category</h1>
			</div>
		</div>
	</div>
</div><!-- Page Banner End -->
<div class="page-breadcrumb fix">
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<ul>
					<li><a href="">Home</a></li>
					<li><span>Add Category</span></li>
				</ul>
			</div>
		</div>
	</div>
</div>
<!-- About Page Start -->
<div class="about-page page margin-70 fix">
	<div class="container">
		<div class="row">
       <center><h3 style="color:orange">Add Category</h3></center>
       <br>
            <form action="" method="post">
           {% csrf_token %}
          <div class="col-md-12">
              <div class="col-lg-4">

              </div>
              <div class="col-lg-4">
                  <input class="form-control" type="text" placeholder="Enter Name" name="cat">

              </div>
              <div class="col-lg-4">

              </div>
          </div>
<br><br><br>
           <div class="row">
               <center>
             <input type="submit" value="Add Category" class="btn btn-info">
               </center>
           </div>
           </form>

		</div>

	</div>
</div><!-- About Page End -->
{% endblock %}

FashionHub/shopping/templates/add_subcat.html
{% extends 'base2.html' %}
{% block body %}
{% load static %}
<style>
	.page-banner {
  background: rgba(0, 0, 0, 0) url("{% static 'img/background/shop-banner.jpg' %}") no-repeat center center;
  -webkit-background-size: cover;
  background-size: cover;
  text-align: center;
}
</style>
<!-- Page Banner Start -->
<div class="page-banner padding-120 fix">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<h1>Add Sub-Category</h1>
			</div>
		</div>
	</div>
</div><!-- Page Banner End -->
<div class="page-breadcrumb fix">
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<ul>
					<li><a href="">Home</a></li>
					<li><span>Add Sub-Category</span></li>
				</ul>
			</div>
		</div>
	</div>
</div>
<!-- About Page Start -->
<div class="about-page page margin-70 fix">
	<div class="container">
		<div class="row">
       <center><h3 style="color:orange">Add Sub-Category</h3></center>
       <br>
            <form action="" method="post" enctype="multipart/form-data">
           {% csrf_token %}
                <div class="col-md-12">
              <div class="col-lg-4">

              </div>
              <div class="col-lg-4">
                  <select name="cid" class="form-control">
                      {% for i in allcat %}
                      <option value="{{ i.id }}">{{ i.name }}</option>
                      {% endfor %}
                  </select>
              </div><br><br><br>
              <div class="col-lg-4">

              </div>
          </div>
          <div class="col-md-12">
              <div class="col-lg-4">

              </div>
              <div class="col-lg-4">
                  <input class="form-control" type="text" placeholder="Enter Name" name="subcat">
                     <br><br>
              </div>
              <div class="col-lg-4">

              </div>
          </div>
<br><br><br>
           <div class="row">
               <center>
             <input type="submit" value="Add Category" class="btn btn-info">
               </center>
           </div>
           </form>

		</div>

	</div>
</div><!-- About Page End -->
{% endblock %}

FashionHub/shopping/templates/all_order.html
{% extends 'base2.html' %}
{% block body %}
{% load static %}
<style>
	.page-banner {
  background: rgba(0, 0, 0, 0) url("{% static 'img/background/shop-banner.jpg' %}") no-repeat center center;
  -webkit-background-size: cover;
  background-size: cover;
  text-align: center;
}
</style>
<!-- Page Banner Start -->
<div class="page-banner padding-120 fix">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<h1>All Orders</h1>
			</div>
		</div>
	</div>
</div><!-- Page Banner End -->
<div class="page-breadcrumb fix">
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<ul>
					<li><a href="">Home</a></li>
					<li><span>All Orders</span></li>
                    </ul>
			</div>
		</div>
	</div>
</div>
<!-- About Page Start -->
<div class="about-page page margin-70 fix">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="table-responsive">
					<table class="table cart-table">
						<thead>
							<tr>
								<th class="width-1">S.no.</th>
								<th class="width-2">Product Name</th>
								<th class="width-6">Number of Orders</th>
                                <th class="width-6">Product Detail</th>
								<th class="width-6">User List</th>

							</tr>
						</thead>
						<tbody>
							{% for i in all_ordered_product %}
							<tr class="carttr_1">

								<td >
									<div class="cartpage-pro-dec">
										<center><a href="">{{ forloop.counter }}</a></center>

									</div>
								</td>
								<td>
									<div class="cart-page-price">
										<h5>{{ i.name }}</h5>
									</div>
								</td>

								<td>
									<div class="cartpage-delete-item">
                                        <h5>{{ i.order_placed_set.count }} Order</h5>
										</div>
								</td>
                                <td>
									<div class="cart-page-price">
                                        <button class="btn btn-warning"><a href="{% url 'product_detail' i.id %}">Details</a></button>
									</div>
								</td>
								<td>
									<div class="cart-page-price">
                                        <button class="btn btn-info"><a href="{% url 'user_list' i.id %}">User List</a></button>
									</div>
								</td>

							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>

			</div>
		</div>

	</div>
</div><!-- About Page End -->
{% endblock %}

FashionHub/shopping/templates/mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>Hello,{{ name }}</h3>
<li>Product Name:{{ product }}</li>
<li>Product Price:{{ price }}</li>
<p>Description: {{ des }}</p>
<br>
<b>Thanks</b>
</body>
</html>

FashionHub/shopping/templates/products.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
<style>
	.page-banner {
  background: rgba(0, 0, 0, 0) url("{% static 'img/background/shop-banner.jpg' %}") no-repeat center center;
  -webkit-background-size: cover;
  background-size: cover;
  text-align: center;
}
</style>
<!-- Page Banner Start -->
<div class="page-banner padding-120 fix">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<h1>{{ subcat.name }}</h1>
			</div>
		</div>
	</div>
</div><!-- Page Banner End -->
<!-- Shop Page Area Start -->
<div class="shop-page page margin-70 fix">
	<div class="container">
		<div class="row">
			<!-- Shop Tool Bar -->
			<div class="col-xs-12 fix">
				<div class="shpo-tool-bar fix">
					<ul class="view-mode float-left">
						<li class="active"><a href="shop.html#pro-grid" data-toggle="tab"><i class="fa fa-th"></i></a></li>
						<li><a href="shop.html#pro-list" data-toggle="tab"><i class="fa fa-th-list"></i></a></li>
					</ul>
					<div class="sort-by float-left">
						<span>Sort By</span>
						<select name="sort-by">
							<option value="mercede" selected="selected">price: Lower</option>
							<option value="saab">price(low&gt;high)</option>
							<option value="mercedes">price(high &gt; low)</option>
							<option value="audi">rating(highest)</option>
						</select>
					</div>
					<div class="show-product float-left">
						<span>Show</span>
						<select name="sort-by">
							<option value="mercede" selected="selected">16</option>
							<option value="saab">20</option>
							<option value="mercedes">24</option>
						</select>
						<span>Per Page</span>
					</div>
					<div class="showing-pro float-right">
						<span>Showing 1 - 12 of 16 items</span>
					</div>
				</div>
			</div>
			<div class="products-container tab-products-container tab-content float-left fix">
				<div class="tab-pane active" id="pro-grid">
					<!-- Single Product -->
					{% for i in subcat.product_set.all %}
					<div class="col-sm-4 col-md-3 col-xs-12">
						<div class="single-product">
							<div class="pro-image-hover">
								<a href="shop.html#" class="pro-image">
									<img class="primary" src="{{ i.img1.url }}" alt="" />
								</a>
								<div class="action-buttons">
									{% if request.user.is_authenticated %}
									<a href="{% url 'cart' i.id %}" ><button class="act-btn add-cart"><i class="fa fa-shopping-basket"></i></button></a>
									{% else %}
									<a href="{% url 'login' %}" ><button class="act-btn add-cart"><i class="fa fa-shopping-basket"></i></button></a>
									{% endif %}
								</div>
							</div>
							<div class="pro-bref fix">
								<a class="pro-name" href="{% url 'product_detail' i.id %}">{{ i.name }}</a>
								<div class="pro-ratting float-left">
									<i class="fa fa-star on"></i>
									<i class="fa fa-star on"></i>
									<i class="fa fa-star on"></i>
									<i class="fa fa-star on"></i>
									<i class="fa fa-star"></i>
								</div>
								<div class="pro-price float-right"><span class="new">&#8377;{{ i.price }}</span></div>
							</div>
						</div>
					</div>
					{% endfor %}<!-- Single Product -->
				</div>
			<div class="col-xs-12">
				<div class="paginations text-center">
					<ul>
						<li class="prev"><a href="shop.html#"><i class="fa fa-angle-left"></i></a></li>
						<li class="active"><span>1</span></li>
						<li><a href="shop.html#">2</a></li>
						<li><a href="shop.html#">3</a></li>
						<li><a href="shop.html#">4</a></li>
						<li class="next"><a href="shop.html#"><i class="fa fa-angle-right"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
</div><!-- Shop page Area End -->
{% endblock %}