New_TechSim/New_TechSim/urls.py
from django.conf.urls import url
from django.contrib import admin
from New_Home.views import *

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home, name="home"),
    url(r'^TechSim/Login/$', Login, name="login"),
    url(r'^TechSim/Logout/$', Logout, name="logout"),
    url(r'^TechSim/Register/$', Register, name="register"),
    url(r'^TechSim/Contact-Us/$', ContactUs, name="contact"),
    url(r'^TechSimPLUS_New_Batches_and_Workshops/$', Event_List, name="all_events"),
    url(r'^(?P<course>[\w-]+)/$', Courses_Details, name="course_details"),
    url(r'^Events/(?P<events>[\w-]+)/$', Events_Details, name="events_details"),


    # Admin Panel Url's
url(r'^TechSim/Admin/Dashboard/$', Admin_Home, name="admin_home"),
url(r'^TechSim/Admin/Banners/$', All_Banners, name="banners"),
url(r'^TechSim/Admin/Add_New_Banner/$', Add_New_Banner, name="Add_New_Banner"),
url(r'^TechSim/Admin/Edit_New_Banner/(?P<b_id>[\w-]+)/(?P<type>[\w-]+)/$', Edit_New_Banner, name="edit_New_Banner"),

url(r'^TechSim/Admin/Courses_Categories/(?P<type>[\w-]+)/(?P<c_id>[\w-]+)/$', All_Courses_Categories, name="courses_categories"),
url(r'^TechSim/Admin/Courses/(?P<type>[\w-]+)/(?P<c_id>[\w-]+)/$', All_Courses, name="courses"),
url(r'^TechSim/Admin/Trainers/(?P<type>[\w-]+)/(?P<t_id>[\w-]+)/$', All_Trainers, name="trainers"),
url(r'^TechSim/Admin/Content/(?P<type>[\w-]+)/(?P<c_id>[\w-]+)/$', All_Content, name="content"),

url(r'^TechSim/Admin/Event_Categories/(?P<type>[\w-]+)/(?P<c_id>[\w-]+)/$', All_Events_Categories, name="events_categories"),
url(r'^TechSim/Admin/Events/(?P<type>[\w-]+)/(?P<c_id>[\w-]+)/$', All_Events, name="events"),
url(r'^TechSim/Admin/Add_Events/$', Add_New_Date, name="add_event_date"),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

New_TechSim/New_Home/models.py
from django.db import models
from django.contrib.auth.models import User

class Slider(models.Model):
    img = models.FileField(null=True, blank=True)
    l1 = models.CharField(max_length=500, null=True, blank=True)
    l2 = models.CharField(max_length=500, null=True, blank=True)
    l3 = models.CharField(max_length=500, null=True, blank=True)
    p = models.CharField(max_length=10, null=True, blank=True)

    def __str__(self):
        return self.p

class Trainer(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    review = models.IntegerField(null=True, blank=True)
    position = models.CharField(max_length=200, null=True, blank=True)
    des = models.CharField(max_length=2000, null=True, blank=True)
    mail = models.CharField(max_length=200, null=True, blank=True)
    img = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.name

class Courses_Category(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    date = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name

class Course(models.Model):
    cat = models.ForeignKey(Courses_Category, related_name="cat",null=True, blank=True, on_delete=models.CASCADE)
    cat2 = models.ForeignKey(Courses_Category, related_name="cat2", null=True, blank=True, on_delete=models.CASCADE)
    t1 = models.ForeignKey(Trainer, related_name="Main", null=True, blank=True, on_delete=models.CASCADE)
    t2 = models.ForeignKey(Trainer, related_name="Secondary", null=True, blank=True, on_delete=models.CASCADE)
    url = models.CharField(max_length=500, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    img = models.FileField(null=True, blank=True)
    fee = models.CharField(max_length=200, null=True, blank=True)
    review = models.IntegerField( null=True, blank=True)
    short_des = models.CharField(max_length=1000, null=True, blank=True)
    long_des = models.CharField(max_length=2000, null=True, blank=True)
    seo_des = models.CharField(max_length=2000, null=True, blank=True)
    seo_keys = models.CharField(max_length=2000, null=True, blank=True)
    duration = models.CharField(max_length=200, null=True, blank=True)
    skill = models.CharField(max_length=200, null=True, blank=True)
    students = models.CharField(max_length=200, null=True, blank=True)
    classes = models.CharField(max_length=200, null=True, blank=True)
    l1 = models.CharField(max_length=200, null=True, blank=True)
    l2 = models.CharField(max_length=200, null=True, blank=True)
    l3 = models.CharField(max_length=200, null=True, blank=True)
    l4 = models.CharField(max_length=200, null=True, blank=True)
    l5 = models.CharField(max_length=200, null=True, blank=True)
    l6 = models.CharField(max_length=200, null=True, blank=True)
    l7 = models.CharField(max_length=200, null=True, blank=True)
    l8 = models.CharField(max_length=200, null=True, blank=True)
    l9 = models.CharField(max_length=200, null=True, blank=True)
    l10 = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name


class Title(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    p = models.CharField(max_length=200, null=True, blank=True)
    S1 = models.CharField(max_length=200, null=True, blank=True)
    S2 = models.CharField(max_length=200, null=True, blank=True)
    S3 = models.CharField(max_length=200, null=True, blank=True)
    S4 = models.CharField(max_length=200, null=True, blank=True)
    S5 = models.CharField(max_length=200, null=True, blank=True)
    S6 = models.CharField(max_length=200, null=True, blank=True)
    S7 = models.CharField(max_length=200, null=True, blank=True)
    S8 = models.CharField(max_length=200, null=True, blank=True)
    S9 = models.CharField(max_length=200, null=True, blank=True)
    S10 = models.CharField(max_length=200, null=True, blank=True)
    S11 = models.CharField(max_length=200, null=True, blank=True)
    S12 = models.CharField(max_length=200, null=True, blank=True)
    S13 = models.CharField(max_length=200, null=True, blank=True)
    S14 = models.CharField(max_length=200, null=True, blank=True)
    S15 = models.CharField(max_length=200, null=True, blank=True)


class Event_Category(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    date = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name


class Events(models.Model):
    usr = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    un = models.CharField(max_length=100, null=True, blank=True)
    ps = models.CharField(max_length=100, null=True, blank=True)

    cat = models.ForeignKey(Event_Category, on_delete=models.CASCADE, null=True, blank=True)
    img = models.FileField(null=True, blank=True)
    logo = models.FileField(null=True, blank=True)
    title = models.CharField(max_length=500, null=True, blank=True)
    url = models.CharField(max_length=500, null=True, blank=True)
    address = models.CharField(max_length=500, null=True, blank=True)
    call = models.CharField(max_length=50, null=True, blank=True)
    email = models.CharField(max_length=50, null=True, blank=True)
    map = models.CharField(max_length=2000, null=True, blank=True)
    topic = models.CharField(max_length=200, null=True, blank=True)
    host = models.CharField(max_length=200, null=True, blank=True)
    file = models.FileField(null=True, blank=True)
    duration = models.CharField(max_length=200, null=True, blank=True)
    skill = models.CharField(max_length=200, null=True, blank=True)
    file_url = models.CharField(max_length=500, null=True, blank=True)
    short_des = models.CharField(max_length=1000, null=True, blank=True)
    long_des = models.CharField(max_length=2000, null=True, blank=True)
    seo_des = models.CharField(max_length=2000, null=True, blank=True)
    seo_keys = models.CharField(max_length=2000, null=True, blank=True)
    students = models.CharField(max_length=2000, null=True, blank=True)
    l1 = models.CharField(max_length=200, null=True, blank=True)
    l2 = models.CharField(max_length=200, null=True, blank=True)
    l3 = models.CharField(max_length=200, null=True, blank=True)
    l4 = models.CharField(max_length=200, null=True, blank=True)
    l5 = models.CharField(max_length=200, null=True, blank=True)
    l6 = models.CharField(max_length=200, null=True, blank=True)
    l7 = models.CharField(max_length=200, null=True, blank=True)
    l8 = models.CharField(max_length=200, null=True, blank=True)
    l9 = models.CharField(max_length=200, null=True, blank=True)
    l10 = models.CharField(max_length=200, null=True, blank=True)
    fee = models.CharField(max_length=200, null=True, blank=True)
    time = models.CharField(max_length=200, null=True, blank=True)
    c_num = models.CharField(max_length=200, null=True, blank=True)
    n1 = models.CharField(max_length=200, null=True, blank=True)
    d1 = models.CharField(max_length=200, null=True, blank=True)
    w1 = models.CharField(max_length=200, null=True, blank=True)
    s1 = models.FileField(null=True, blank=True)
    n2 = models.CharField(max_length=200, null=True, blank=True)
    d2 = models.CharField(max_length=200, null=True, blank=True)
    w2 = models.CharField(max_length=200, null=True, blank=True)
    s2 = models.FileField(null=True, blank=True)
    n3 = models.CharField(max_length=200, null=True, blank=True)
    d3 = models.CharField(max_length=200, null=True, blank=True)
    w3 = models.CharField(max_length=200, null=True, blank=True)
    s3 = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.title


class Dates(models.Model):
    Event = models.ForeignKey(Events, on_delete=models.CASCADE, null=True, blank=True)
    certificate = models.BooleanField(default=False)
    start_date = models.DateField(max_length=200, null=True, blank=True)
    end_date = models.DateField(max_length=200, null=True, blank=True)
    date = models.CharField(max_length=200, null=True, blank=True)

New_TechSim/New_Home/templates/Home/course_details.html
{% extends 'Home/base.html' %}
{% load static %}
{% block body %}
<!-- Content -->
    <div class="page-content bg-white">
        <!-- inner page banner -->
        <div class="page-banner ovbl-dark" style="background-image:url({{ i.img.url }});">
            <div class="container">
                <div class="page-banner-entry">
                    <h1 class="text-white">{{ i.name }}</h1>
				 </div>
            </div>
        </div>
		<!-- Breadcrumb row -->
		<div class="breadcrumb-row">
			<div class="container">
				<ul class="list-inline">
					<li><a href="{% url 'home' %}">Home</a></li>
					<li><a href="">Courses</a></li>
					<li>{{ i.cat.name }}</li>
					<li>{{ i.name }}</li>
				</ul>
			</div>
		</div>
	<div class="content-block">
            <!-- About Us -->
			<div class="section-area section-sp1">
                <div class="container">
					 <div class="row d-flex flex-row-reverse">
						<div class="col-lg-3 col-md-4 col-sm-12 m-b30">
							<div class="course-detail-bx">
								<div class="course-price">
									<h4 class="price">&#8377; {{ i.fee }}</h4>
								</div>
								<div class="course-buy-now text-center">
									<a href="courses-details.html#" class="btn radius-xl text-uppercase">Buy Now This Courses</a>
								</div>
								<div class="teacher-bx">
									<div class="teacher-info">
										<div class="teacher-thumb">
											<img src="{{ i.img.url }}" alt=""/>
										</div>
										<div class="teacher-name">
											<h5>{{ i.t1.name }}</h5>
											<span>{{ i.t1.position }}</span>
										</div>
									</div>
								</div>
								<div class="cours-more-info">
									<div class="review">
										<span>Review Rating</span>
										<ul class="cours-star">
											{% if i.review >= 1 %}
														<li class="active"><i class="fa fa-star"></i></li>
													{% else %}
														<li><i class="fa fa-star"></i></li>
													{% endif %}

													{% if i.review >= 2 %}
														<li class="active"><i class="fa fa-star"></i></li>
													{% else %}
														<li><i class="fa fa-star"></i></li>
													{% endif %}

													{% if i.review >= 3 %}
														<li class="active"><i class="fa fa-star"></i></li>
													{% else %}
														<li><i class="fa fa-star"></i></li>
													{% endif %}

													{% if i.review >= 4 %}
														<li class="active"><i class="fa fa-star"></i></li>
													{% else %}
														<li><i class="fa fa-star"></i></li>
													{% endif %}

													{% if i.review >= 5 %}
														<li class="active"><i class="fa fa-star"></i></li>
													{% else %}
														<li><i class="fa fa-star"></i></li>
													{% endif %}
										</ul>
									</div>
									<div class="price categories">
										<span>Categories</span>
										<h6 class="text-primary">{{ i.cat.name }}</h6>
									</div>
								</div>
								<div class="course-info-list scroll-page">
									<ul class="navbar">
										<li><a class="nav-link" href="#overview"><i class="ti-zip"></i>Overview</a></li>
										<li><a class="nav-link" href="#curriculum"><i class="ti-bookmark-alt"></i>Curriculum</a></li>
										<li><a class="nav-link" href="#instructor"><i class="ti-user"></i>Instructor</a></li>
										<li><a class="nav-link" href="#reviews"><i class="ti-comments"></i>Reviews</a></li>
									</ul>
								</div>
							</div>
						</div>

						<div class="col-lg-9 col-md-8 col-sm-12">
							<div class="courses-post">
								<div class="ttr-post-media media-effect">
									<a href="courses-details.html#"><img src="{{ i.img.url }}" alt=""></a>
								</div>
								<div class="ttr-post-info">
									<div class="ttr-post-title ">
										<h2 class="post-title">{{ i.name }}</h2>
									</div>
									<div class="ttr-post-text">
										<p>{{ i.short_des }}</p>
									</div>
								</div>
							</div>
							<div class="courese-overview" id="overview">
								<h4>Overview</h4>
								<div class="row">
									<div class="col-md-12 col-lg-4">
										<ul class="course-features">
											<li><i class="ti-book"></i> <span class="label">Lectures</span> <span class="value">{{ i.classes }}</span></li>
											<li><i class="ti-time"></i> <span class="label">Duration</span> <span class="value">{{ i.duration }}</span></li>
											<li><i class="ti-hand-point-right"></i> <span class="label">MemberShip</span> <span class="value">Yes</span></li>
											<li><i class="ti-layout-grid3-alt"></i> <span class="label">Projects</span> <span class="value">Yes</span></li>
											<li><i class="ti-stats-up"></i> <span class="label">Skill level</span> <span class="value">{{ i.skill }}</span></li>
											<li><i class="ti-smallcap"></i> <span class="label">Language</span> <span class="value">English</span></li>
											<li><i class="ti-user"></i> <span class="label">Students</span> <span class="value">{{ i.students }}</span></li>
											<li><i class="ti-check-box"></i> <span class="label">Assessments</span> <span class="value">Yes</span></li>
										</ul>
									</div>
									<div class="col-md-12 col-lg-8">
										<h5 class="m-b5">Course Description</h5>
										<p>{{ i.long_des }}</p>
										<h5 class="m-b5">Learning Outcomes</h5>
										<ul class="list-checked primary">
											<li>Over 37 lectures and 55.5 hours of content!</li>
											<li>LIVE PROJECT End to End Software Testing Training Included.</li>
											<li>Learn Software Testing and Automation basics from a professional trainer from your own desk.</li>
											<li>Information packed practical training starting from basics to advanced testing techniques.</li>
											<li>Best suitable for beginners to advanced level users and who learn faster when demonstrated.</li>
											<li>Course content designed by considering current software testing technology and the job market.</li>
											<li>Practical assignments at the end of every session.</li>
											<li>Practical learning experience with live project work and examples.cv</li>
										</ul>
									</div>
								</div>
							</div>
							<div class="m-b30" id="curriculum">
								<h4>Curriculum</h4>
								<ul class="curriculum-list">
									{% for c in i.title_set.all %}
									<li>
											<h5 style="color:black;">Step - {{ forloop.counter }}: {{ c.name }}</h5>
											<ul>
												{% if c.S1 %}<li>{{ c.S1 }}</li>{% endif %}
												{% if c.S2 %}<li>{{ c.S2 }}</li>{% endif %}
												{% if c.S3 %}<li>{{ c.S3 }}</li>{% endif %}
												{% if c.S4 %}<li>{{ c.S4 }}</li>{% endif %}
												{% if c.S5 %}<li>{{ c.S5 }}</li>{% endif %}
												{% if c.S6 %}<li>{{ c.S6 }}</li>{% endif %}
												{% if c.S7 %}<li>{{ c.S7 }}</li>{% endif %}
												{% if c.S8 %}<li>{{ c.S8 }}</li>{% endif %}
												{% if c.S9 %}<li>{{ c.S9 }}</li>{% endif %}
												{% if c.S10 %}<li>{{ c.S10 }}</li>{% endif %}
												{% if c.S11 %}<li>{{ c.S11 }}</li>{% endif %}
												{% if c.S12 %}<li>{{ c.S12 }}</li>{% endif %}
												{% if c.S13 %}<li>{{ c.S13 }}</li>{% endif %}
												{% if c.S14 %}<li>{{ c.S14 }}</li>{% endif %}
												{% if c.S15 %}<li>{{ c.S15 }}</li>{% endif %}
											</ul>
										</li>
										{% endfor %}
									</ul>
							</div>
							<div class="" id="instructor">
								<h4>Instructor</h4>
								<div class="instructor-bx">
									<div class="">
										<img src="{{ i.t1.img.url }}" style="border-radius:90%;" width="200" alt="">
									</div>
									<div class="instructor-info">
										<h6>{{ i.t1.name }}</h6>
										<span>{{ i.t1.position }}</span>
										<p class="m-b0">{{ i.t1.des }}</p>
									</div>
								</div>
								{% if i.t2 %}
								<div class="instructor-bx">
									<div class="">
										<img src="{{ i.t2.img.url }}" style="border-radius:90%;" width="200" alt="">
									</div>
									<div class="instructor-info">
										<h6>{{ i.t2.name }}</h6>
										<span>{{ i.t2.position }}</span>
										<p class="m-b0">{{ i.t2.des }}</p>
									</div>
								</div>
								{% endif %}
							</div>
						</div>

					</div>
				</div>
            </div>
        </div>
		<!-- contact area END -->

    </div>
    <!-- Content END-->

{% endblock %}

New_TechSim/New_Home/templates/Home/event_details.html
{% extends 'Home/base.html' %}
{% load static %}
{% block body %}
<!-- Content -->
    <div class="page-content bg-white">
        <!-- inner page banner -->
        <div class="page-banner ovbl-dark" style="background-image:url({% static 'TechSim/img3.jpg' %});">
            <div class="container">
                <div class="page-banner-entry">
                    <h1 class="text-white">{{ i.title }}</h1>
				 </div>
            </div>
        </div>

		<div class="breadcrumb-row">
			<div class="container">
				<ul class="list-inline">
					<li><a href="{% url 'home' %}">Home</a></li>
					<li><a href="{% url 'all_events' %}">Events</a></li>
					<li>Courses Details</li>
				</ul>
			</div>
		</div>
		<!-- Breadcrumb row END -->
        <!-- inner page banner END -->
		<div class="content-block">
            <!-- About Us -->
			<div class="section-area section-sp1">
                <div class="container">
					 <div class="row">
						<div class="col-lg-8 col-md-7 col-sm-12">
							<div class="courses-post">
								<div class="ttr-post-media media-effect">
									<a href="events-details.html#"><img src="{{ i.img.url }}" alt=""></a>
								</div>
								<div class="ttr-post-info">
									<div class="ttr-post-title ">
										<h2 class="post-title">{{ i.title }}</h2>
									</div>
									<div class="ttr-post-text">
										<p>{{ i.short_des }}</p></div>
								</div>
							</div>
							<div class="courese-overview" id="overview">
								<div class="row">
									<div class="col-md-12 col-lg-5">
										<ul class="course-features">
											<li><i class="ti-book"></i> <span class="label">Topics</span> <span class="value">{{ i.topic }}</span></li>
											<li><i class="ti-blackboard"></i> <span class="label">Starting</span> <span class="value">
												{% for d in i.dates_set.all %}
													{% if d.start_date > today %}
															{{ d.start_date }}<br>
													{% endif %}
												{% endfor %}</span></li>
											<li><i class="ti-layout-column3-alt"></i> <span class="label">Duration</span><span class="value">{{ i.duration }}</span></li>
							 {% if i.time %}<li><i class="ti-time"></i> <span class="label">Time</span><span class="value">{{ i.time }}</span></li>{% endif %}
											<li><i class="ti-stats-up"></i> <span class="label">Skill level</span> <span class="value">{{ i.skill }}</span></li>
											<li><i class="ti-smallcap"></i> <span class="label">Language</span> <span class="value">English</span></li>
											<li><i class="ti-user"></i> <span class="label">Students</span> <span class="value">{{ i.students }}</span></li>
											<li><i class="ti-check-box"></i> <span class="label">Assessments</span> <span class="value">Yes</span></li>
										</ul>
									</div>
									<div class="col-md-12 col-lg-7">
										<h5 class="m-b5">Event Description</h5>
										<p>{{ i.long_des }}</p>
										<h5 class="m-b5">Event Content</h5>
										<ul class="list-checked primary">
											{% if i.l1 %}<li>{{ i.l1 }}</li>{% endif %}
												{% if i.l2 %}<li>{{ i.l2 }}</li>{% endif %}
												{% if i.l3 %}<li>{{ i.l3 }}</li>{% endif %}
												{% if i.l4 %}<li>{{ i.l4 }}</li>{% endif %}
												{% if i.l5 %}<li>{{ i.l5 }}</li>{% endif %}
												{% if i.l6 %}<li>{{ i.l6 }}</li>{% endif %}
												{% if i.l7 %}<li>{{ i.l7 }}</li>{% endif %}
												{% if i.l8 %}<li>{{ i.l8 }}</li>{% endif %}
												{% if i.l9 %}<li>{{ i.l9 }}</li>{% endif %}
												{% if i.l10 %}<li>{{ i.l10 }}</li>{% endif %}
										</ul>
										<center><button class="btn btn-success" style="border-radios:50%;
										 background-color:#6C3483"><span style="color:white;">Get Register</span></button></center>
									</div>


								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-5 col-sm-12 m-b30">
							<div class="bg-primary text-white contact-info-bx m-b30">
								<h2 class="m-b10 title-head">Fee:<span></span></h2>
								<div class="course-price">
									<h4 class="price">&#8377; {{ i.fee }}</h4>
								</div>
								<h2 class="m-b10 title-head">Contact <span>Information</span></h2>
								<p>Unique physical platform to attend this Event with your peers</p>
								<div class="widget widget_getintuch">
									<ul>
										<li><i class="ti-location-pin"></i>{{ i.address }}</li>
										<li><i class="ti-mobile"></i>{{ i.call }}</li>
										<li><i class="ti-email"></i>{{ i.email }}</li>
									</ul>
								</div>
								<center><button class="btn" style="background-color:white;"><span style="color:red;">Get Register</span></button></center>
							</div>
							{{ i.map | safe }}
						</div>
					</div>
				</div>
            </div>
        </div>
		<!-- contact area END -->

    </div>
    <!-- Content END-->

{% endblock %}